	SUBROUTINE TENSPRO(TV,TM)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
	DIMENSION TM(6,6), TV(6)
C
	DO I=1,6
		DO J=1,6
		TM(I,J)=0.0
		ENDDO
	ENDDO
C	
	DO I=1,6
		DO J=1,6
		TM(I,J)=TV(I)*TV(J)
		ENDDO
	ENDDO
C
	RETURN
	END
	
	SUBROUTINE TENSPRO6(AB,A,B)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
	DIMENSION AB(6,6), A(6), B(6)
C	
	DO I=1,6
		DO J=1,6
		AB(I,J)=A(I)*B(J)
		ENDDO
	ENDDO
C
	RETURN
	END
	
	SUBROUTINE TENSPRO6f(AB,A,B,fact)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
	DIMENSION AB(6,6), A(6), B(6)
C	
	DO I=1,6
		DO J=1,6
		AB(I,J)=A(I)*B(J)*fact
		ENDDO
	ENDDO
C
	RETURN
	END
	
	SUBROUTINE TENSPRO6p(AB,CD,A,B)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
	DIMENSION AB(6,6), CD(6,6), A(6), B(6)
C	
	DO I=1,6
		DO J=1,6
		AB(I,J)=CD(I,J)+A(I)*B(J)
		ENDDO
	ENDDO
C
	RETURN
	END
	
	SUBROUTINE TENSPRO6m(AB,CD,A,B)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
	DIMENSION AB(6,6), CD(6,6), A(6), B(6)
C	
	DO I=1,6
		DO J=1,6
		AB(I,J)=CD(I,J)-A(I)*B(J)
		ENDDO
	ENDDO
C
	RETURN
	END

	SUBROUTINE TENSPRO6pf(AB,CD,A,B,fact)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
	DIMENSION AB(6,6), CD(6,6), A(6), B(6)
C	
	DO I=1,6
		DO J=1,6
		AB(I,J)=CD(I,J)+A(I)*B(J)*fact
		ENDDO
	ENDDO
C
	RETURN
	END
	
	SUBROUTINE TENSPRO6mf(AB,CD,A,B,fact)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
	DIMENSION AB(6,6), CD(6,6), A(6), B(6)
C	
	DO I=1,6
		DO J=1,6
		AB(I,J)=CD(I,J)-A(I)*B(J)*fact
		ENDDO
	ENDDO
C
	RETURN
	END